version: '3.7'
services:
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.8
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    container_name: kafka
    image: debezium/kafka:1.8
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - ADVERTISED_HOST_NAME=192.168.1.221

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  connect:
    container_name: connect
    image: debezium/connect:1.8
    ports:
      - 8083:8083
    links:
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - GROUP_ID=settlement-debezium-connect
      - CONNECT_PRODUCER_MAX_REQUEST_SIZE=3145728
