version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=pgusr
      - POSTGRES_PASSWORD=pgpw
      - POSTGRES_DB=payment
    ports:
      - 5432:5432
    container_name: postgres
