server:
  port: 8085
spring:
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: postgres
